# Generated by Django 4.1.1 on 2022-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='is_currently_testing',
            field=models.BooleanField(default=False, help_text='States if engineer is currently testing', verbose_name='testing status'),
        ),
    ]
