# Generated by Django 4.1.1 on 2022-09-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_engineers_rename_createcustomer_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineers',
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerASIN',
            field=models.CharField(max_length=100),
        ),
    ]
